#!/usr/bin/env bash
docker image rm -f rmdmetropolis
docker build -t rmdmetropolis .
docker build -t example ./example
docker run example
docker cp $(docker ps -alq):/home/example/example.pdf ./example/example.pdf
