#!/usr/bin/env bash
# docker image rm -f rmdmetro
docker build --platform linux/amd64 -t rmdmetro .
docker build --platform linux/amd64 -t binbexample ./binb-example
docker run --platform linux/amd64 binbexample
docker cp $(docker ps -alq):/home/binb-example/myslides/myslides.pdf ./binb-example/myslides/myslides.pdf
